### ISSUE TITLE
error when using data.table setnames(): ALTSTRING classes must provide a Set_elt method

### ISSUE THREAD

**Issue by emilBeBri** [traversc/qs#9] opened 2019-06-15 07:46 UTC
when saving a data.table with qsave, no matter which preset compression, and then using setnames() from data.table, the following error pops out:

`
Error in setnames(føl1, føl_reg$dan_s, føl_reg$dan) : 
  ALTSTRING classes must provide a Set_elt method
`
This error doesn't happen if setnames() is used directly on the data.table before it is saved and read with qsave/qread. 

however by copying the DT with copy()  then the error disappears. The error also disappears when creating a new variable, even by reference like so:
`DT[, var := 1L]`

but it doesn't disapper just by making another reference to the same object with 
`DT_copy <- DT`
, and it doesn't disappear by using setcolorder() before doing the setnames(). however, setcolorder works, it just doesn't change whatever needs to be changed in order for setnames() to work correctly.

I can't figure out which variables it is that creates this problem, since a simple 1 column data.table with a character vector does not create the error. 

the dataset with the error attached, and can also be downloaded here:
https://www.dropbox.com/s/16bhw6eplywcoej/egne_f%C3%B8lelser_datasheet.xlsx?dl=0

[egne_følelser_datasheet.xlsx](https://github.com/traversc/qs/files/3292841/egne_folelser_datasheet.xlsx)

**Comment by traversc** [comment] 2019-06-15 08:27
I see what the problem is.  

I don't think it's necessarily a bug with `qs` because `data.table` is calling C functions directly, but it will be fixed soon :)  

For now, when you read in the data, use the parameter `use_alt_rep=F` for now.  

```
library(qs)
library(readxl)
library(data.table)

setwd("~/Downloads")
x <- read_excel("egne_folelser_datasheet.xlsx")
x <- data.table(x)
qsave(x, file="temp.qs")
z <- qread("temp.qs", use_alt_rep = F)
setnames(z, 1, "hi") # no error hopefully
```

**Comment by emilBeBri** [comment] 2019-06-16 07:37
allright, great!
And thank you for a great package - better than feather AND fst, but with the flexibility with object-types from RDS - awesome!

**Comment by emilBeBri** [comment] 2019-06-16 07:38
should I close the issue? I'm not that familiar with the procedures about these things.

**Comment by traversc** [comment] 2019-06-16 07:40
I believe I've fixed the issue using altrep if you want to use it.  

tbh, altrep doesn't really make too much difference, it's more for winning benchmarks :p

Feel free to re-open if there's still an issue.

**Closed by traversc** 2019-06-16 07:40 UTC
